### ISSUE TITLE
Better description when failed to connect Couchbase

### ISSUE THREAD

**Issue by tomyeh** [rikulo/couchclient#5]
The current message is as follows. It is hard to know what causes it:

```
Uncaught Error: SocketIOException: Connection failed (OS Error: No connection could be made because the target machine actively refused it.
, errno = 10061)
Stack Trace:
#0      _NativeSocket.connect.<anonymous closure> (dart:io-patch/socket_patch.dart:124:9)
#1      _ThenFuture._sendValue (dart:async/future_impl.dart:265:24)
#2      _FutureImpl._setValue (dart:async/future_impl.dart:149:26)
#3      _FutureListenerWrapper._sendValue (dart:async/future_impl.dart:65:21)
#4      _FutureImpl._setValue (dart:async/future_impl.dart:149:26)
#5      _FutureImpl._setOrChainValue (dart:async/future_impl.dart:239:16)
#6      _ThenFuture._sendValue (dart:async/future_impl.dart:271:21)
#7      _FutureImpl._setValue (dart:async/future_impl.dart:149:26)
#8      _FutureImpl._setOrChainValue (dart:async/future_impl.dart:239:16)
#9      _ThenFuture._sendValue (dart:async/future_impl.dart:271:21)
#10     _FutureImpl._setValue (dart:async/future_impl.dart:149:26)
#11     _SyncCompleter._setFutureValue (dart:async/future_impl.dart:43:21)
#12     _Completer.complete (dart:async/future_impl.dart:12:20)
#13     _SendPortImpl.call.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:106:27)
#14     _ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:81:92)
```

**Comment by tomyeh** [comment]
Won't fix.
